name: anti-ad-clash

on:
  schedule:
    - cron: 0 18 * * *
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2


    - name: Run 
      run: |
        wget https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-domains.txt
        echo "payload:" > anti-ad-clash.yaml
        for domain in $(cat ./anti-ad-domains.txt);do
          echo "  - DOMAIN-SUFFIX,$domain" >> anti-ad-clash.yaml
        done
        rm -rf ./anti-ad-domains.txt
        git config --global user.email "18576718+Eccon@users.noreply.github.com"
        git config --global user.name "Eccon"
        git add .
        git commit -m "Update Anti-AD-Clash Rule"
        git push --force 
