name: CI

on:
  #schedule:
  #  - cron: 0 20 * * *
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    #- uses: actions/checkout@v2
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        wget https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt
        chmod +x ./shell.sh
        ./shell.sh > china_ip_list.rsc
        rm -rf china_ip_list.txt
        git -f push 
