name: CI

on:
  #schedule:
  #  - cron: 0 20 * * *
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Run 
      run: |
        wget https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt
        chmod +x ./shell.sh
        ./shell.sh > china_ip_list.rsc
        rm -rf china_ip_list.txt
        git push --force 
